name: Build and Test Library Management System

on:
  workflow_dispatch: # Trigger workflow manually from the Actions tab

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Set up JDK
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin' # Specify the Java distribution

    # Compile the Java code
    - name: Compile Library Management System
      run: javac LibraryManagementSystem.java

    # Run the application to ensure it works
    - name: Test Library Management System
      run: |
        echo "Testing the application..."
        java LibraryManagementSystem <<EOF
        5
        EOF

    # Build the Docker image
    - name: Build Docker Image
      run: docker build -t library-management-system .

    # Test the Dockerized application
    - name: Run Docker Container
      run: |
        echo "Testing the Docker container..."
        docker run -it library-management-system <<EOF
        5
        EOF
